spring:
  application:
    name: bank-rest-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bank_rest_service
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${auth0.domain}/"

logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.liquibase: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  file:
    name: application.log
    max-size: 10MB
    max-history: 5

server:
  port: 8080

auth0:
  domain: ${AUTH0_DOMAIN}
  jwks-url: "https://${auth0.domain}/.well-known/jwks.json"
  audience: ${AUTH0_AUDIENCE}

bank:
  cards:
    pan-hash-secret: ${BANK_CARDS_PAN_HASH_SECRET}

springdoc:
  package-to-scan: com.example.bankcards.controller
  tagsSorting: alpha
  api-docs:
    path: /api-docs.yaml
  swagger-ui:
    path: /swagger-ui.html