@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Debit Cards System - Containers

Person(customer, "Customer/Admin", "Пользователь")

System_Boundary(s1, "Cards System") {
  Container(web, "Web UI", "Фронтенд в браузере")
  Container(api, "Core API", "Spring Boot", "REST API + бизнес-логика")
  ContainerDb(db, "PostgreSQL", "DB", "Карты, пользователи, транзакции")
}

System_Ext(auth0, "Auth0", "Identity Provider")

Rel(customer, auth0, "Логин, получает JWT", "HTTPS")
Rel(customer, web, "Работает с UI", "HTTPS")
Rel(web, api, "REST API + Bearer JWT", "HTTPS")
Rel(api, auth0, "Валидирует JWT (JWK Set)", "HTTPS")
Rel(api, db, "CRUD", "JDBC")

@enduml